export const SITE = {
  website: "https://womanintech-spec.github.io/portfolio/",
  author: "Barbara Teslar",
  profile: "https://github.com/WomaninTech-spec",
  desc: "Platform Engineering Manager spécialisée dans l'IA. Je pilote des équipes et des plateformes où humains et agents IA collaborent pour accélérer la delivery.",
  title: "Barbara Teslar — Platform Engineering Manager IA",
  ogImage: "og-image.png",
  lightAndDarkMode: true,
  postPerIndex: 4,
  postPerPage: 6,
  scheduledPostMargin: 15 * 60 * 1000,
  showArchives: true,
  showBackButton: true,
  editPost: { enabled: false, text: "", url: "" },
  dynamicOgImage: true,
  dir: "ltr",
  lang: "fr",
  timezone: "Europe/Paris",
};